sudo: required
language: node_js
node_js:
  - 13

services: 
  - docker

before_install:
  - docker build -t pasha/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pasha/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-089795933593"
  bucket_path: "Dockerreact"
  on: 
    branch : master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
